-- OSBUNK 2.0.2
local C={name='OSBUNK',version='2.0.2',pin='2580',bunker={door='front',lights='back',ventilation='left',alarm='bottom'}}
if fs.exists('/config.lua') then local ok,x=pcall(dofile,'/config.lua'); if ok and type(x)=='table' then for k,v in pairs(x) do C[k]=v end end end
local M=peripheral.find('monitor'); local T=M or term.current(); if M then pcall(M.setTextScale,0.5) end
local S={locked=true,door=true,lights=true,vent=true,alarm=false,lockdown=false}; local pin=''; local L={os.date('%H:%M:%S')..'  BOOT'}
local function log(x)table.insert(L,1,os.date('%H:%M:%S')..'  '..x);while #L>60 do table.remove(L)end end
local function beep()local s=peripheral.find('speaker');if s then pcall(s.playNote,'pling',0.7,12)end end
local function say(x)beep();log(x)end
local function out(n,v)local side=C.bunker and C.bunker[n];if side and side~='none' then pcall(redstone.setOutput,side,v)end end
local function apply()out('door',S.door);out('lights',S.lights);out('ventilation',S.vent);out('alarm',S.alarm)end
local function clear(bg)T.setBackgroundColor(bg or colors.black);T.setTextColor(colors.white);T.clear()end
local function w(x,y,s,fg,bg)if bg then T.setBackgroundColor(bg)end;if fg then T.setTextColor(fg)end;T.setCursorPos(x,y);local W=T.getSize();T.write(tostring(s):sub(1,math.max(0,W-x+1)))end
local function fill(x,y,ww,hh,c)T.setBackgroundColor(c);for yy=y,y+hh-1 do T.setCursorPos(x,yy);T.write(string.rep(' ',ww))end end
local function btn(x,y,ww,hh,s,c,fg)fill(x,y,ww,hh,c or colors.gray);w(x+math.max(0,math.floor((ww-#s)/2)),y+math.floor(hh/2),s,fg or colors.white,c or colors.gray)end
local function center(y,s,fg,bg)local W=T.getSize();w(math.max(1,math.floor((W-#s)/2)+1),y,s,fg,bg)end
local function head(s)local W=T.getSize();fill(1,1,W,2,colors.blue);w(2,1,C.name..' // '..C.version,colors.white,colors.blue);w(2,2,s,colors.white,colors.blue)end
local function lockScreen()clear();local _,h=T.getSize();fill(1,1,T.getSize(),3,colors.blue);center(2,'OSBUNK SECURITY',colors.white,colors.blue);center(5,'ENTER PIN',colors.cyan);center(6,string.rep('*',#pin));local k={{'1',2,8},{'2',12,8},{'3',22,8},{'4',2,11},{'5',12,11},{'6',22,11},{'7',2,14},{'8',12,14},{'9',22,14},{'CLR',2,17},{'0',12,17},{'OK',22,17}};for _,v in ipairs(k)do if v[2]<=T.getSize() and v[3]<=h then btn(v[2],v[3],8,2,v[1])end end end
local apps={{'CTRL','Control'},{'HW','Hardware'},{'NET','Network'},{'PRINT','Printer'},{'DRIVE','Drive'},{'LOG','Logs'},{'FILE','Files'},{'TERM','Shell'}}
local function desktop()clear();local W,H=T.getSize();head('BUNKER DESKTOP');for i,a in ipairs(apps)do local x=2+(i-1)%4*14;local y=4+math.floor((i-1)/4)*5;if y+3<H then btn(x,y,11,3,a[1]);w(x,y+3,a[2],colors.white)end end;fill(1,H-2,W,3,colors.blue);btn(2,H-1,9,2,'START',colors.lightBlue,colors.black);w(14,H-1,S.lockdown and 'LOCKDOWN' or 'SECURE',S.lockdown and colors.red or colors.lime,colors.blue);w(math.max(1,W-10),H-1,os.date('%H:%M:%S'),colors.white,colors.blue)end
local function setDoor(v)if S.lockdown and not v then say('LOCKDOWN: door locked');return end;S.door=v;out('door',v);log(v and 'DOOR LOCKED' or 'DOOR OPEN')end
local function alarm(v)S.alarm=v;out('alarm',v);log(v and 'ALARM ACTIVE' or 'ALARM CLEAR')end
local function lockDown(v)S.lockdown=v;if v then S.door=true;S.lights=true;S.vent=true;S.alarm=true;apply();say('!!! LOCKDOWN ACTIVE !!!')else S.alarm=false;apply();say('LOCKDOWN CLEARED')end end
local function control()while true do clear();local W,H=T.getSize();head('CONTROL CENTER');w(2,4,'DOOR',colors.cyan);w(18,4,S.door and 'LOCKED' or 'OPEN',S.door and colors.lime or colors.yellow);w(2,5,'LIGHTS',colors.cyan);w(18,5,S.lights and 'ON' or 'OFF');w(2,6,'VENTILATION',colors.cyan);w(18,6,S.vent and 'ON' or 'OFF');w(2,7,'ALARM',colors.cyan);w(18,7,S.alarm and 'ACTIVE' or 'CLEAR',S.alarm and colors.red or colors.lime);btn(2,9,14,2,'DOOR');btn(18,9,14,2,'LIGHTS');btn(2,12,14,2,'VENT');btn(18,12,14,2,'ALARM');btn(2,15,30,2,S.lockdown and 'CLEAR LOCKDOWN' or 'EMERGENCY LOCKDOWN',S.lockdown and colors.orange or colors.red);w(2,H-1,'D/L/V/A | E emergency | ESC back',colors.lightGray);local e={os.pullEvent()};if e[1]=='key' then local k=e[2];if k==keys.esc then return elseif k==keys.d then setDoor(not S.door)elseif k==keys.l then S.lights=not S.lights;out('lights',S.lights)elseif k==keys.v then S.vent=not S.vent;out('ventilation',S.vent)elseif k==keys.a then alarm(not S.alarm)elseif k==keys.e then lockDown(not S.lockdown)end elseif e[1]=='mouse_click' or e[1]=='monitor_touch' then local x,y=e[3],e[4];if y>=9 and y<=10 and x<16 then setDoor(not S.door)elseif y>=9 and y<=10 and x>=18 then S.lights=not S.lights;out('lights',S.lights)elseif y>=12 and y<=13 and x<16 then S.vent=not S.vent;out('ventilation',S.vent)elseif y>=12 and y<=13 and x>=18 then alarm(not S.alarm)elseif y>=15 and y<=16 then lockDown(not S.lockdown)end end end end
local function hardware()clear();head('HARDWARE');local _,H=T.getSize();local y=4;for _,n in ipairs(peripheral.getNames())do if y<=H-3 then w(2,y,n,colors.cyan);w(20,y,tostring(peripheral.getType(n)));y=y+1 end end;if y==4 then w(2,y,'No peripherals',colors.yellow)end;w(2,H-1,'ESC back',colors.lightGray);while true do local e={os.pullEvent('key')};if e[2]==keys.esc then return end end end
local function network()local m=peripheral.find('modem');if not m then clear();head('NETWORK');w(2,5,'No modem detected',colors.yellow);sleep(2);return end;local side=peripheral.getName(m);rednet.open(side);while true do clear();head('NETWORK');w(2,4,'MODEM',colors.cyan);w(18,4,side,colors.lime);w(2,5,'COMPUTER ID',colors.cyan);w(18,5,os.getComputerID());btn(2,8,28,2,'BROADCAST HELLO');w(2,12,'ESC back',colors.lightGray);local e={os.pullEvent()};if e[1]=='key' and e[2]==keys.esc then rednet.close(side);return elseif e[1]=='mouse_click' or e[1]=='monitor_touch' then if e[4]>=8 and e[4]<=9 then rednet.broadcast('OSBUNK ONLINE ID='..os.getComputerID(),'OSBUNK');say('Broadcast sent')end end end end
local function printer()local p=peripheral.find('printer');if not p then clear();head('PRINTER');w(2,5,'Printer not found',colors.yellow);sleep(2);return end;while true do clear();head('PRINTER');w(2,4,'Printer ready',colors.lime);btn(2,8,28,2,'PRINT REPORT');w(2,12,'ESC back',colors.lightGray);local e={os.pullEvent()};if e[1]=='key' and e[2]==keys.esc then return elseif (e[1]=='mouse_click' or e[1]=='monitor_touch') and e[4]>=8 and e[4]<=9 then local ok,new=pcall(p.newPage);if not ok or not new then say('No paper/ink')else pcall(p.setPageTitle,'OSBUNK Report');pcall(p.write,'OSBUNK '..C.version);pcall(p.setCursorPos,1,3);pcall(p.write,'Computer ID: '..os.getComputerID());pcall(p.setCursorPos,1,5);pcall(p.write,'Time: '..os.date());pcall(p.setCursorPos,1,7);pcall(p.write,'Door: '..(S.door and 'LOCKED' or 'OPEN'));pcall(p.setCursorPos,1,8);pcall(p.write,'Lights: '..(S.lights and 'ON' or 'OFF'));pcall(p.endPage);say('Report printed')end end end end
local function drive()local d=peripheral.find('drive');if not d then clear();head('DISK DRIVE');w(2,5,'Disk drive not found',colors.yellow);sleep(2);return end;clear();head('DISK DRIVE');w(2,5,'Drive: '..peripheral.getName(d),colors.cyan);local present=false;pcall(function()present=d.isDiskPresent()end);w(2,6,present and 'DISK INSERTED' or 'EMPTY',present and colors.lime or colors.yellow);w(2,12,'ESC back',colors.lightGray);while true do local e={os.pullEvent('key')};if e[2]==keys.esc then return end end end
local function logs()clear();head('EVENT LOG');local _,H=T.getSize();for i=1,math.min(#L,H-4)do w(2,i+2,L[i],i==1 and colors.yellow or colors.lightGray)end;w(2,H-1,'ESC back',colors.lightGray);while true do local e={os.pullEvent('key')};if e[2]==keys.esc then return end end end
local function files()local path='/';while true do clear();head('FILES '..path);local _,H=T.getSize();local a=fs.list(path);table.sort(a);for i,n in ipairs(a)do if i<=H-5 then w(2,i+2,(fs.isDir(fs.combine(path,n)) and '[DIR] ' or '')..n)end end;w(2,H-1,'BACKSPACE up | ESC',colors.lightGray);local e={os.pullEvent('key')};if e[2]==keys.esc then return elseif e[2]==keys.backspace and path~='/' then path=fs.getDir(path);if path=='' then path='/' end elseif e[2]==keys.enter and #a>0 and fs.isDir(fs.combine(path,a[1])) then path=fs.combine(path,a[1])end end end
local function run(id)if id=='CTRL'then control()elseif id=='HW'then hardware()elseif id=='NET'then network()elseif id=='PRINT'then printer()elseif id=='DRIVE'then drive()elseif id=='LOG'then logs()elseif id=='FILE'then files()elseif id=='TERM'then shell.run('shell')end end
apply()
while true do
 if S.locked then lockScreen() else desktop() end
 local e={os.pullEvent()}
 if S.locked then
  if e[1]=='key' then local k=e[2];if k==keys.enter then if pin==tostring(C.pin)then S.locked=false;pin='';say('ACCESS GRANTED')else pin='';say('INVALID PIN')end elseif k==keys.backspace then pin=pin:sub(1,-2)elseif k>=keys.zero and k<=keys.nine then pin=pin..tostring(k-keys.zero)elseif k==keys.q then break end
  elseif e[1]=='mouse_click' or e[1]=='monitor_touch' then local x,y=e[3],e[4];local n={{'1',2,8},{'2',12,8},{'3',22,8},{'4',2,11},{'5',12,11},{'6',22,11},{'7',2,14},{'8',12,14},{'9',22,14},{'CLR',2,17},{'0',12,17},{'OK',22,17}};for _,v in ipairs(n)do if x>=v[2]and x<v[2]+8 and y>=v[3]and y<v[3]+2 then if v[1]=='CLR'then pin=''elseif v[1]=='OK'then if pin==tostring(C.pin)then S.locked=false;pin='';say('ACCESS GRANTED')else pin='';say('INVALID PIN')end else pin=pin..v[1]end end end end
  end
 else
  if e[1]=='key'then if e[2]==keys.q then break elseif e[2]==keys.l then S.locked=true elseif e[2]==keys.e then lockDown(not S.lockdown)end elseif e[1]=='mouse_click'or e[1]=='monitor_touch'then local x,y=e[3],e[4];local H=T.getSize();if y>=H-1 and x>=2 and x<=10 then local id='START';clear();head('START');for i,a in ipairs(apps)do w(4,4+i*2,a[1]..'  '..a[2])end;local q={os.pullEvent()};if q[1]=='key'and q[2]==keys.esc then desktop()elseif q[1]=='mouse_click'or q[1]=='monitor_touch'then local i=math.floor((q[4]-5)/2);if apps[i]then run(apps[i][1])end end else local id;for i,a in ipairs(apps)do local ax=2+(i-1)%4*14;local ay=4+math.floor((i-1)/4)*5;if x>=ax and x<ax+11 and y>=ay and y<ay+4 then id=a[1]end end;if id then run(id)end end end
 end
end
setAlarm(false)
